# Header
menu:
  Home: /
  # My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

# User Info
user_name: Humingkang
user_avatar: https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1965250681,3772762698&fm=26&gp=0.jpg
user_location: Earth
user_description: "A personal Blog"
user_contact: 616131924@qq.com
user_introduction: "小前端一名"

github_username: 616131924
twitter_username:
weibo_username:
zhihu_username:
facebook_username:
linkedin_username:

# Content
excerpt_link: 
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: false
livere_uid: null

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Highlight code
# do ensure u have closed all the highlight choices in ur root _config.yml
# currently we provided 6 choices based on highlight script
# highlight_default, highlight_light, highlight_github, highlight_rainbow, highlight_vs, highlight_atom
block_highlight: highlight_rainbow
